TestMVC5/Models/Customers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customers
    {    // Préciser la clé primère et l'auto incrmenter  (normalement ca n'a pas de sens cause deja fait dans labase sql)  DbFirst!!!
        //[Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CustomerId { get; set; }

        [Display( Name= "Customer Name" )]
        [Required(ErrorMessage ="Erreur : le nom est obligatoire!!")]
        public string FirstName { get; set; }

        [Display(Name = "TEST")]
        [Required(ErrorMessage = "Erreur : le prénom est obligatoire!!")]
        public string LastName { get; set; }

        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Invoice { get; set; }
        public string CustomerOpinion { get; set; }

    }
}

TestMVC5/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcDatasetEntities : DbContext
    {
        public MvcDatasetEntities()
            : base("name=MvcDatasetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
    }
}

TestMVC5/Models/Model1.Designer.cs
// La génération de code T4 est activée pour le modèle 'C:\Users\SlimBELTAIEF\Desktop\Projets\TestMVC5\TestMVC5\Models\Model1.edmx'. 
// Pour activer la génération de code héritée, définissez la valeur de la propriété
// du concepteur 'Stratégie de génération de code' sur 'ObjectContext hérité'. Cette propriété est disponible dans la fenêtre Propriétés lorsque le modèle
//  est ouvert dans le concepteur.

// Si aucun contexte et classe d'entité n'a été généré, c'est peut-être parce que vous avez créé un modèle vide, mais
// que vous n'avez pas encore choisi la version d'Entity Framework à utiliser. Pour générer une classe de contexte et des classes
// d'entité pour le modèle, ouvrez le modèle dans le concepteur, cliquez avec le bouton droit sur l'aire de conception, puis
// sélectionnez 'Mettre à jour le modèle à partir de la base de données...', 'Générer une base de données à partir du modèle...' ou 'Ajouter un élément de génération
// de code...'.

TestMVC5/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

TestMVC5/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestMVC5.Models;
using TestMVC5.Services;

namespace TestMVC5.Controllers
{
    public class CustomersController : Controller
    {
        private readonly CustomersServices  _services = new CustomersServices();

        MvcDatasetEntities db = new MvcDatasetEntities();
        // GET: Customers
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Liste()
        {
            //Je demande au controleur de récupérer la liste des Customers du Model apres la View affiche ce quelle veut et de ca facon 
            //var customers = db.Customers.ToList();
            //return View(customers);

            // Or using services
            //if (ModelState.IsValid)
            //{
            //    _services.ToListing();
            //}


            //    return View();
            return View(db.Customers.ToList());
            //return View();
        }

        // la vue ou il ya le formulaire d'ajout
        public ActionResult AddCustomer()
        {
            return View();
        }

        ///dedans il ya la vue qui gére le formulaire
        // cette vue va nous permettre d'ajouter un client

        //COMPARER LES DEUX M2THODES / AVEC PARAMETRES / SANS PARAMETRES

        //[HttpPost]
        //public ActionResult SaveNewCustomer(int id, string nom, string prenom, int age, decimal facture, string message)
        //{
        //    var client = new Customers()
        //    {
        //        FirstName = nom,
        //        LastName = prenom,
        //        Age = age,
        //        Invoice = facture,
        //        CustomerOpinion = message
        //    };

        //    db.Customers.Add(client);
        //    db.SaveChanges();
        //    // RedirectToAction("Liste") et non pas View("Liste")!!!!!!!!!!
        //    return RedirectToAction("Liste");
        //}


        [HttpPost]
        public ActionResult SaveNewCustomer(Customers client)
        {

            if (ModelState.IsValid)
            {

                _services.AddNewCustomer(client);
                // si le model est valid( dont les conditions REQUIRED Sont respectés ) on retourne vers notre Liste ...
                return RedirectToAction("Liste");

            }
            // sinon onreste sur la vue pour afficher les erreurs (les coriger)
            return View("AddCustomer");

        }

        // Test 
        //[HttpPost]
        //public ActionResult AddCustomer(Customers client)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        _services.AddNewCustomer(client);

        //    }

        //    return View();
        //}

        //Ce message d’erreur est créé automatiquement par le framework de validation à partir de ce que nous avons dans le modèle 
        //////////Ici on voulait utiliser la méthode  (ViewBag.MessageErreur) mais ca ne fonctionne pas !!!!!!!!!//////////////////////////
        //if (string.IsNullOrWhiteSpace(client.LastName))
        //{
        //    ViewBag.MessageErreur("Vous devez remplir ce champ");

        //}
        // AddNewCustomer est une méthode qui se trouve dans le dossier Sevices

        public ActionResult DeleteCustomer(int id)
        {

            _services.ToDeleteCustomer(id);

            return RedirectToAction("Liste");
        }


        // Détails du client

        public ActionResult DetailsCustomer(int Id)
        {
              ////////////////////////////////////////////////////////////////////////////////////////////////////////
             /////////// Stocker le résultat de la requéte services afin de l'envoyer à la vue////////////////////////
             /////////////////////////////////////////////////////////////////////////////////////////////////////////
           var client =  _services.DisplayCustomerDetails(Id);

            return View(client);

        }


        public ActionResult DropDown()
        {
            var liste = _services.ToListing();

            return View(liste);
        }
    }
}

TestMVC5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestMVC5.Controllers
{
    public class HomeController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestMVC5/Views/Customers/AddCustomer.cshtml
@model TestMVC5.Models.Customers

@{
    ViewBag.Title = "AddCustomer";
}

<center>
    <h2 style="color: green">You Can Add  New Customers</h2>

     
    @using (Html.BeginForm("SaveNewCustomer", "Customers", FormMethod.Post))
    {
    <div class="hs">
        @*1) EN UTILISANT DisplayNameFor et TextBoxFor /   DisplayFor ne fonctionne pas ?????????????? : A Voir !!!*@
        <h1> <span>@Html.DisplayNameFor(model => model.FirstName)</span> </h1>
        @Html.TextBoxFor(model => model.FirstName, new { @style = "width:75%;", @class = "form-control", placeholder = "First Name" })<br />
        @Html.ValidationMessageFor(model => model.FirstName)
        <h1> <span>@Html.DisplayNameFor(model => model.LastName)</span> </h1>
        @Html.TextBoxFor(model => model.LastName, new { @style = "width:75%;", @class = "form-control", placeholder = "Last Name" })<br />
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        @*////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///Ce message d’erreur est créé automatiquement par le framework de validation à partir de ce que nous avons dans le modèle///
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////*@

        @* //<h4>@Html.ValidationMessageFor(model => model.LastName)</h4>
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////*@
        <h1> <span>@Html.DisplayNameFor(model => model.Age)</span> </h1>
        @Html.TextBoxFor(model => model.Age, new { @style = "width:75%;", @class = "form-control", placeholder = "Age" })
        <h1><span> @Html.DisplayNameFor(model => model.Invoice) </span></h1>
        @Html.TextBoxFor(model => model.Invoice, new { @style = "width:75%;", @class = "form-control", placeholder = "Invoice" })
        <h1><span>  @Html.DisplayNameFor(model => model.CustomerOpinion)</span> </h1>
        @Html.TextBoxFor(model => model.CustomerOpinion, new { @style = "width:75%;", @class = "form-control", placeholder = "msg" })
        <br />
       <input type="submit" id="bouton17" name="name" value="Add" class="label-danger" />

      @* //////////////////////////////////////////////////// TESTER UN JOLI BOUTON ///V/////////////////////////////////////
        ///                                                                                                              ///





        // 2)) //  UTILISER DIRECTEMENT UN EditorFor QUI VA GENERER UN FORMULAIRE QUI CONTIENT TOUTES LES PROPRIETES DU MODEL
        // COMMENT SUPPRIMER LA PROPRIETE CustomerId DU FORULAIRE???????????????????????????????? utiliser id dans la méthode???? : A faire

        //@Html.EditorFor(model => model, new { htmlAttributes = new { @class = "form-control", placeholder = "Name" } })
        //ici on change le CSS de notre imput (EditurFor)
        //<input type="submit" name="name" value="Add Customer" />

        // 3))  //UTILISER LES INPUTS SANS PASSER PAR LES DATANOTATIONS
        // IL FAUT PRECISER LE NOM  DE LA PROPRIETE

        <input type="text" name="FirstName" value="" class="" />
        <input type = "text" name="LastName" value="" class="" />
        <input type = "text" name="age" value="" class="" />
        <input type = "text" name="Invoice" value="" class="" />
        <input type="text" name="CustomerOpinion" value="" class="" />
        <input type="submit" name="name" value="Add Customer" />*@
    </div>
    }

</center>

TestMVC5/Views/Customers/DetailsCustomer.cshtml
@model TestMVC5.Models.Customers

@{
    ViewBag.Title = "DetailsCustomer";
}


<h1 style="border: 3px solid black">DetailsCustomer</h1>
<hr /><hr /><hr />
<strong>@Html.DisplayFor(m => m.FirstName)</strong>
<hr />
<strong>@Html.DisplayFor(m => m.LastName)</strong>
<hr />
<strong>@Html.DisplayFor(m => m.Age)</strong>
<hr />
<strong>@Html.DisplayFor(m => m.Invoice)</strong>
<hr />
<strong>@Html.DisplayFor(m => m.CustomerOpinion)</strong>
<hr />

TestMVC5/Views/Customers/DropDown.cshtml
@model IEnumerable<TestMVC5.Models.Customers>

    @{
        ViewBag.Title = "DropDown";
    }

    <h2>DropDown</h2>

    <select size="1">
       @if(Model != null)
       {
           foreach(var client in Model)
           {
               <option> @Html.DisplayFor(m => client.FirstName)</option>
           }
       }


    </select>

TestMVC5/Views/Customers/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h1>Bonjour : cette page va vous permettre d'accéder au avis de nos clients</h1>
@Html.ActionLink("The Customers List", "Liste", "Customers")
<hr /><hr /><hr />
<p><a href="http://localhost:62422/Customers/Liste" class="btn btn-primary btn-lg">The Customers List &raquo;</a></p>

<hr /><hr /><hr />

@*<div class="madiv">
        <div class="wrapper">
            <a class="cta" href="http://localhost:62422/Customers/Liste">
                <span>List</span>
                <span>
                    <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                            <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                            <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
                        </g>
                    </svg>
                </span>
            </a>
        </div>
    </div>

    <hr /><hr /><hr />*@

<p><a href="http://localhost:62422/Customers/AddCustomer" class="btn btn-primary btn-lg">New Customer &raquo;</a></p>

<!--
<div class="wrapper">
    <a class="cta" href="http://localhost:62422/Customers/AddCustomer">
        <span>Add</span>
        <span>
            <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                    <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                    <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
                </g>
            </svg>
        </span>
    </a>
</div>-->
<hr /><hr /><hr />
<p><a href="http://localhost:62422/Customers/DropDown" class="btn btn-primary btn-lg">Dropdown for Customers &raquo;</a></p>

TestMVC5/Views/Customers/Liste.cshtml
@model IEnumerable<TestMVC5.Models.Customers>

@{
    ViewBag.Title = "Liste";
}

<strong>THIS IS THE UPDATED CUSTOMER LIST</strong>
<hr /><hr />
@*
    @if (Model != null)
    {
        foreach (var person in Model)
        {
            //@Html.DisplayNameFor(mperson => person.FirstName)    Ne fonctionne pas ??!!!!!!!!!!
            <h3>Nom du Client : @Html.DisplayFor(mperson => person.FirstName)</h3>
            <h5> @string.Format("Avis de la personne {0}:{1} ", person.CustomerId, @person.CustomerOpinion)</h5><hr /><hr />
        }

    }
*@

@* Afficher les résultat dans un tableau*@
@if (Model != null)
{
    {

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(m => m.FirstName)</th>
                <th scope="col"> @Html.DisplayNameFor(m => m.LastName)</th>
                <th scope="col"> @Html.DisplayNameFor(m => m.Age)</th>
                <th scope="col"> @Html.DisplayNameFor(m => m.Invoice)</th>
                <th scope="col"> @Html.DisplayNameFor(m => m.CustomerOpinion)</th>
                <th scope="col"> Delete Customer</th>
                <th scope="col"> Details Customer</th>


            </tr>
        </thead>
        @foreach (var person in Model)
        {
            <tbody>
                <tr>
                    <th scope="row">@Html.DisplayFor(mperson => person.FirstName)</th>
                    <td>@Html.DisplayFor(mperson => person.LastName)</td>
                    <td>@Html.DisplayFor(mperson => person.Age)</td>
                    <td>@Html.DisplayFor(mperson => person.Invoice)</td>
                    <td>@Html.DisplayFor(mperson => person.CustomerOpinion)</td>
                    @*  definir le paramertre id qui est dans la méthode,   on précise pas le controleur !! *@
                    @*new { id = person.CustomerId } routeValues*@
                    <td>@Html.ActionLink("Delete", "DeleteCustomer", new { id = person.CustomerId }, new { onclick = "return confirm('Are you sure you wish to delete this customer?');" })</td>
                    @*For Customer Details*@
                    <td>@Html.ActionLink("Details", "DetailsCustomer", new { Id = person.CustomerId })</td>
                </tr>

            </tbody>
        }
    </table>

     }
}

TestMVC5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestMVC5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";

}


<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

@Html.Partial("~/Views/Home/About.cshtml")

TestMVC5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestMVC5/Views/Home/SlimIndex.cshtml
@{
    ViewBag.Title = "SlimIndex";
}

<h2>SlimIndex</h2>


<h1>>@ViewBag.Message</h1>

TestMVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Customers Area", "Index", "Customers")</li>
                    @*<li>@Html.ActionLink("Customers Details", "DropDownDetails", "Customers")</li>*@
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()
    <div class="container body-content">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)



</body>
</html>